In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression 

In [2]:
df=pd.read_csv(r"C:\Users\dell\Documents\apprentissage_ML_DL_Python_R_udemy\codes\House_price_prepros_class.csv",header=0)

In [3]:
df

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0     24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1     21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2     34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3     33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4     36.2       32.18     0.458     7.147  54.2      21.3       5.33   
..     ...         ...       ...       ...   ...       ...        ...   
501   22.4       41.93     0.573     6.593  69.1      19.0       9.67   
502   20.6       41.93     0.573     6.120  76.7      19.0       9.08   
503   23.9       41.93     0.573     6.976  91.0      19.0       5.64   
504   22.0       41.93     0.573     6.794  89.3      19.0       6.48   
505   19.0       41.93     0.573     6.030  80.8      19.0       7.88   

     airportYES  n_hos_beds  n_hot_rooms  waterbodyLake  \
0             1       5.480     11.19200              0   
1             0       7.332     12.17280              1   
2             0       7.394     46.19856              0   
3             1       9.268     11.26720              1   
4             0       8.824     11.28960              1   
..          ...         ...          ...            ...   
501           0       9.348     12.17920              0   
502           1       6.612     13.16480              0   
503           0       5.478     12.19120              0   
504           1       7.940     15.17600              0   
505           1      10.280     10.15200              0   

     waterbodyLake and River  waterbodyRiver  rainfall     parks  Sold  \
0                          0               1        23  0.049347     0   
1                          0               0        42  0.046146     1   
2                          0               0        38  0.045764     0   
3                          0               0        45  0.047151     0   
4                          0               0        55  0.039474     0   
..                       ...             ...       ...       ...   ...   
501                        1               0        27  0.056006     1   
502                        1               0        20  0.059903     1   
503                        0               0        31  0.057572     1   
504                        0               0        47  0.060694     1   
505                        0               0        45  0.060336     1   

     moy_dist  
0      4.0875  
1      4.9675  
2      4.9675  
3      6.0650  
4      6.0625  
..        ...  
501    2.4775  
502    2.2875  
503    2.1675  
504    2.3900  
505    2.5050  

[506 rows x 17 columns]

### Logistic Regression 
#### simple

##### on veut prédir la variable y=sold en fonction de price=X

In [4]:
# X 2 dim car sklearn requière X 2 dim
X=df[['price']]
X

price
0     24.0
1     21.6
2     34.7
3     33.4
4     36.2
..     ...
501   22.4
502   20.6
503   23.9
504   22.0
505   19.0

[506 rows x 1 columns]

In [5]:
y=df['Sold']
y

0      0
1      1
2      0
3      0
4      0
      ..
501    1
502    1
503    1
504    1
505    1
Name: Sold, Length: 506, dtype: int64

In [6]:
# FIRST METHOD
from sklearn.linear_model import LogisticRegression

In [7]:
class_logistic = LogisticRegression()

In [8]:
class_logistic.fit(X,y)

LogisticRegression()

In [9]:
print(class_logistic.intercept_, class_logistic.coef_)

[0.61477516] [[-0.03571865]]


In [10]:
# SECOND METHOD
X_cons=sm.add_constant(X)

In [11]:
X_cons.head()

const  price
0    1.0   24.0
1    1.0   21.6
2    1.0   34.7
3    1.0   33.4
4    1.0   36.2

In [12]:
import statsmodels.discrete.discrete_model as sn

In [13]:
logit=sn.Logit(y,X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5


In [14]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Sun, 01 Aug 2021   Pseudo R-squ.:                 0.01788
Time:                        00:02:00   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

### Logistic Regression 
#### multiple


In [15]:
X_multi=df.loc[:,df.columns!='Sold']

In [16]:
X_multi

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0     24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1     21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2     34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3     33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4     36.2       32.18     0.458     7.147  54.2      21.3       5.33   
..     ...         ...       ...       ...   ...       ...        ...   
501   22.4       41.93     0.573     6.593  69.1      19.0       9.67   
502   20.6       41.93     0.573     6.120  76.7      19.0       9.08   
503   23.9       41.93     0.573     6.976  91.0      19.0       5.64   
504   22.0       41.93     0.573     6.794  89.3      19.0       6.48   
505   19.0       41.93     0.573     6.030  80.8      19.0       7.88   

     airportYES  n_hos_beds  n_hot_rooms  waterbodyLake  \
0             1       5.480     11.19200              0   
1             0       7.332     12.17280              1   
2             0       7.394     46.19856              0   
3             1       9.268     11.26720              1   
4             0       8.824     11.28960              1   
..          ...         ...          ...            ...   
501           0       9.348     12.17920              0   
502           1       6.612     13.16480              0   
503           0       5.478     12.19120              0   
504           1       7.940     15.17600              0   
505           1      10.280     10.15200              0   

     waterbodyLake and River  waterbodyRiver  rainfall     parks  moy_dist  
0                          0               1        23  0.049347    4.0875  
1                          0               0        42  0.046146    4.9675  
2                          0               0        38  0.045764    4.9675  
3                          0               0        45  0.047151    6.0650  
4                          0               0        55  0.039474    6.0625  
..                       ...             ...       ...       ...       ...  
501                        1               0        27  0.056006    2.4775  
502                        1               0        20  0.059903    2.2875  
503                        0               0        31  0.057572    2.1675  
504                        0               0        47  0.060694    2.3900  
505                        0               0        45  0.060336    2.5050  

[506 rows x 16 columns]

In [17]:
y_multi=df['Sold']

In [18]:
help(LogisticRegression())

Help on LogisticRegression in module sklearn.linear_model._logistic object:

class LogisticRegression(sklearn.base.BaseEstimator, sklearn.linear_model._base.LinearClassifierMixin, sklearn.linear_model._base.SparseCoefMixin)
 |  LogisticRegression(penalty='l2', *, dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
 |  
 |  Logistic Regression (aka logit, MaxEnt) classifier.
 |  
 |  In the multiclass case, the training algorithm uses the one-vs-rest (OvR)
 |  scheme if the 'multi_class' option is set to 'ovr', and uses the
 |  cross-entropy loss if the 'multi_class' option is set to 'multinomial'.
 |  (Currently the 'multinomial' option is supported only by the 'lbfgs',
 |  'sag', 'saga' and 'newton-cg' solvers.)
 |  
 |  This class implements regularized logistic regression using the
 |  'liblinear' library, 'newton-cg', '

In [19]:
class_logistic_multi = LogisticRegression(max_iter=1000)
class_logistic_multi.fit(X_multi,y_multi)

LogisticRegression(max_iter=1000)

In [20]:
class_logistic_multi.coef_

array([[-2.54374386e-01, -1.20168896e-04, -1.19934140e+00,
         9.71069377e-01, -4.55156136e-03,  2.69181468e-01,
        -2.09160240e-01, -1.16100883e-01,  1.78261858e-01,
        -7.55233441e-02, -7.06931141e-02, -2.79212623e-02,
         2.11802190e-01, -5.55828053e-03, -2.44980127e-02,
        -3.18689989e-01]])

In [21]:
class_logistic_multi.intercept_

array([-1.85611277])

In [22]:
# 2e method
X_multi_cons=sm.add_constant(X_multi)
X_multi_cons

const  price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0      1.0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1      1.0   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2      1.0   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3      1.0   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4      1.0   36.2       32.18     0.458     7.147  54.2      21.3       5.33   
..     ...    ...         ...       ...       ...   ...       ...        ...   
501    1.0   22.4       41.93     0.573     6.593  69.1      19.0       9.67   
502    1.0   20.6       41.93     0.573     6.120  76.7      19.0       9.08   
503    1.0   23.9       41.93     0.573     6.976  91.0      19.0       5.64   
504    1.0   22.0       41.93     0.573     6.794  89.3      19.0       6.48   
505    1.0   19.0       41.93     0.573     6.030  80.8      19.0       7.88   

     airportYES  n_hos_beds  n_hot_rooms  waterbodyLake  \
0             1       5.480     11.19200              0   
1             0       7.332     12.17280              1   
2             0       7.394     46.19856              0   
3             1       9.268     11.26720              1   
4             0       8.824     11.28960              1   
..          ...         ...          ...            ...   
501           0       9.348     12.17920              0   
502           1       6.612     13.16480              0   
503           0       5.478     12.19120              0   
504           1       7.940     15.17600              0   
505           1      10.280     10.15200              0   

     waterbodyLake and River  waterbodyRiver  rainfall     parks  moy_dist  
0                          0               1        23  0.049347    4.0875  
1                          0               0        42  0.046146    4.9675  
2                          0               0        38  0.045764    4.9675  
3                          0               0        45  0.047151    6.0650  
4                          0               0        55  0.039474    6.0625  
..                       ...             ...       ...       ...       ...  
501                        1               0        27  0.056006    2.4775  
502                        1               0        20  0.059903    2.2875  
503                        0               0        31  0.057572    2.1675  
504                        0               0        47  0.060694    2.3900  
505                        0               0        45  0.060336    2.5050  

[506 rows x 17 columns]

In [23]:
logit_multi=sn.Logit(y_multi,X_multi_cons).fit()

Optimization terminated successfully.
         Current function value: 0.556433
         Iterations 6


In [24]:
logit_multi.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      489
Method:                           MLE   Df Model:                           16
Date:                Sun, 01 Aug 2021   Pseudo R-squ.:                  0.1924
Time:                        00:02:13   Log-Likelihood:                -281.56
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 9.930e-21
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -2.1383      2.649     -0.807      0.420      -7.331       3.054
price                      -0.2741      0.033     -8.313      0.000      -0.339      -0.209
resid_area                  0.0192      0.027      0.720      0.471      -0.033       0.071
air_qual                   -7.4183      2.691     -2.757      0.006     -12.693      -2.144
room_num                    1.1067      0.277      4.001      0.000       0.565       1.649
age                        -0.0020      0.007     -0.302      0.762      -0.015       0.011
teachers                    0.3150      0.064      4.937      0.000       0.190       0.440
poor_prop                  -0.2077      0.034     -6.149      0.000      -0.274      -0.141
airportYES                 -0.1524      0.211     -0.723      0.469      -0.565       0.261
n_hos_beds                  0.1760      0.071      2.467      0.014       0.036       0.316
n_hot_rooms                -0.0742      0.052     -1.439      0.150      -0.175       0.027
waterbodyLake              -0.1032      0.304     -0.340      0.734      -0.698       0.492
waterbodyLake and River    -0.0626      0.328     -0.191      0.849      -0.705       0.580
waterbodyRiver              0.2394      0.256      0.937      0.349      -0.262       0.740
rainfall                   -0.0033      0.008     -0.394      0.693      -0.020       0.013
parks                      29.1089     24.177      1.204      0.229     -18.277      76.495
moy_dist                   -0.4017      0.098     -4.118      0.000      -0.593      -0.211
===========================================================================================
"""

### prediction et matrice de confusion

* reg log simple

In [25]:
# sklearn method
class_logistic.predict_proba(X)
# la colonne 1 contient les proba de 0 et la colonne 2 celles de 1

array([[0.56032285, 0.43967715],
       [0.53910688, 0.46089312],
       [0.6512781 , 0.3487219 ],
       ...,
       [0.55944269, 0.44055731],
       [0.54265485, 0.45734515],
       [0.51596437, 0.48403563]])

In [26]:
print(class_logistic.predict_proba(X).shape)
print(df.shape)

(506, 2)
(506, 17)


In [27]:
y_pred=class_logistic.predict(X)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [28]:
y_pred.shape

(506,)

In [29]:
# par défaut la proba seuille est de 0.5, mais peut être modifier
y_pred_03=(class_logistic.predict_proba(X)[:,1]>=0.3)
y_pred_03

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [53]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [31]:
confusion_matrix(y,y_pred)

array([[208,  68],
       [165,  65]], dtype=int64)

In [32]:
# 208 true negatif, 68 false positive

In [33]:
confusion_matrix(y,y_pred_03)

array([[ 29, 247],
       [  2, 228]], dtype=int64)

## performance metrics

In [34]:
from sklearn.metrics import classification_report

In [35]:
classification_report(y,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.56      0.75      0.64       276\n           1       0.49      0.28      0.36       230\n\n    accuracy                           0.54       506\n   macro avg       0.52      0.52      0.50       506\nweighted avg       0.53      0.54      0.51       506\n'

In [36]:
from sklearn.metrics import precision_score, recall_score

In [37]:
precision_score(y,y_pred)

0.48872180451127817

In [38]:
recall_score(y,y_pred)

0.2826086956521739

In [39]:
from sklearn.metrics import roc_auc_score

In [40]:
roc_auc_score(y,y_pred)

0.5181159420289855

# TRAIN TEST

In [41]:
from sklearn.model_selection import train_test_split

In [45]:
X_train, X_test, y_train, y_test= train_test_split(X_multi,y_multi,test_size=0.2, random_state=0)

In [46]:
print(X_train.shape,y_train.shape,X_test.shape,y_test.shape)

(404, 16) (404,) (102, 16) (102,)


In [50]:
clr_LR=LogisticRegression(max_iter=10000)
clr_LR.fit(X_train,y_train)

LogisticRegression(max_iter=10000)

In [51]:
y_test_pred=clr_LR.predict(X_test)

In [52]:
confusion_matrix(y_test,y_test_pred)

array([[37, 21],
       [12, 32]], dtype=int64)

In [54]:
accuracy_score(y_test,y_test_pred) # % de prediction correcte

0.6764705882352942